# Generated by Django 4.1.3 on 2023-02-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_from',
            new_name='dateFrom',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_to',
            new_name='dateTo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='collect_from',
            new_name='collectFrom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='collect_to',
            new_name='collectTo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_name',
            new_name='companyName',
        ),
    ]
