# Generated by Django 4.1.3 on 2023-02-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_date_from_event_datefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('houseNumber', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('postalCode', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
